import json
import os
from pathlib import Path
import re
import subprocess
import sys
from datetime import datetime, timezone
from dotenv import load_dotenv
from jsonschema import ValidationError, validate
from openai import OpenAI
import argparse
from rich_argparse import RichHelpFormatter
from rich.console import Console
from rich.text import Text
from rich.syntax import Syntax
from rich.panel import Panel
from rich.prompt import Prompt, Confirm

"""Code Generator - Rich CLI Version
================================="""

# Load .env
env_path = Path(__file__).resolve().parents[2] / ".env"
load_dotenv(env_path, override=True)

CONFIG_PATH = Path(__file__).resolve().with_name(".code_generator_rich_config.json")

# Define the console for rich output
console = Console()

# Define the JSON schema for validating the output of the code generation function
JSON_OUTPUT_SCHEMA = {
    "type": "object",
    "properties": {
        "model": {"type": "string", "minLength": 1},
        "client": {"type": "string", "minLength": 1},
        "description": {"type": "string", "minLength": 1},
        "temperature": {"type": "number", "minimum": 0.0, "maximum": 1.0},
        "max_tokens": {"type": "integer", "minimum": 1},
        "with_tests": {"type": "boolean"},
        "created_at": {
            "type": "string",
            "pattern": r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d+Z$",
        },
        "code": {"type": "string"},
        "tests": {"type": "string"},
    },
    "required": [
        "model",
        "client",
        "description",
        "temperature",
        "max_tokens",
        "with_tests",
        "created_at",
        "code",
    ],
    "if": {"properties": {"with_tests": {"const": False}}},
    "then": {"not": {"required": ["tests"]}},
    "additionalProperties": False,
}
# Helper rich formatting function
def format_ollama_model_name(model_name: str) -> Text:
    """Formats model name as green base + blue variant.
    Args:
        model_name (str): The raw model name to format.
    Returns:
        Text: A rich Text object with the formatted model name."""
    if ":" not in model_name:
        return Text(model_name, style="green")

    base_name, variant = model_name.split(":", 1)
    text = Text()
    text.append(base_name, style="green")
    text.append(f":{variant}", style="blue")
    return text

# Helper function to fetch available Ollama models using the CLI
def get_ollama_models() -> list[str]:
    """Returns available Ollama model names using the Ollama CLI.
    Args:
        None
    Returns:
        list[str]: A list of available Ollama model names.
    """
    result = subprocess.run(
        ["ollama", "list"],
        capture_output=True,
        text=True,
        check=True,
        encoding="utf-8",
    )
    lines = [line.strip() for line in result.stdout.splitlines() if line.strip()]
    if len(lines) <= 1:
        return []
    models = []
    for line in lines[1:]:
        parts = line.split()
        if parts:
            models.append(parts[0])
    return models

# Define OpenAI clients for both Ollama and OpenAI API (can be used interchangeably)
ollama_client = OpenAI(
    base_url="http://localhost:11434/v1",
    api_key="ollama",  # required by the client, but Ollama ignores it
)

# Get the Ollama available models
try:
    ollama_models = get_ollama_models()
except Exception as e:
    console.print(f"[yellow]Failed to fetch Ollama models: {e}[/yellow]")
    ollama_models = []

openai_api_key = os.getenv("OPENAI_API_KEY")
openai_client = OpenAI() if openai_api_key else None
client = openai_client or ollama_client

DEFAULT_CONFIG = {
    "client": "openai" if openai_client else "ollama",
    "model": "gpt-4o-mini" if openai_client else (ollama_models[0] if ollama_models else "llama3.2"),
}

# Define helper function to send prompts to the OpenAI API
def ask(prompt, 
        model = "gpt-4o-mini", 
        system=None, 
        temperature=0, 
        max_tokens=500, 
    client=client) -> str:
    """
    Helper function to send a prompt to an OpenAI-compatible API and get a response.
    Args:
        prompt (str): The question or prompt to ask the model.
        model (str, optional): The model to use for the request. Default is "gpt-4o-mini".
        system (str, optional): An optional system message to provide context to the model.
        temperature (float, optional): The sampling temperature to use for the response. Default is 0.
        max_tokens (int, optional): The maximum number of tokens to generate in the response. Default is 1500.
        client (object, optional): The OpenAI-compatible client to use for the request. Default is openai_client.
    Returns:
        str: The response generated by the model.
    """
    #Validate temperature and default
    if not (0.0 <= temperature <= 1.0):
        print("Temperature must be between 0.0 and 1.0")
        print("Using default temperature of 0.0")
        temperature = 0.0
    #Validate max_tokens and default
    if max_tokens <= 0:
        print("max_tokens must be a positive integer")
        print("Using default max_tokens of 500")
        max_tokens = 500
    # Get client    
    try:
        client = client
    except Exception as e:
        raise ValueError(f"Invalid client provided: {e}")
    
    msgs = []
    if system:
        msgs.append({"role": "system", "content": system})
    msgs.append({"role": "user", "content": prompt})
    r = client.chat.completions.create(
        model=model, 
        messages=msgs,
        temperature=temperature, 
        max_tokens=max_tokens
    )
    return r.choices[0].message.content


def load_cli_config() -> dict:
    """Loads persisted CLI defaults from disk if available.
    Args:
        None
    Returns:
        dict: A configuration dictionary with "client" and "model" keys.    
    """
    config = DEFAULT_CONFIG.copy()

    if not CONFIG_PATH.exists():
        return config

    try:
        stored_config = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        console.print(f"[yellow]Ignoring invalid config file at {CONFIG_PATH}: {exc}[/yellow]")
        return config

    if isinstance(stored_config, dict):
        client_name = stored_config.get("client")
        model_name = stored_config.get("model")
        if isinstance(client_name, str):
            config["client"] = client_name
        if isinstance(model_name, str) and model_name.strip():
            config["model"] = model_name.strip()

    return config

def save_cli_config(config: dict) -> None:
    """Persists CLI defaults to disk.
    Args:
        config (dict): The configuration dictionary to save.
    Returns:
        None
    """
    CONFIG_PATH.write_text(json.dumps(config, indent=2), encoding="utf-8")

def get_available_client_names() -> list[str]:
    """Returns the client names that can be used in the current environment.
    Args:
        None
    Returns:
        list[str]: A list of available client names.
    """
    available_clients = ["ollama"]
    if openai_client:
        available_clients.insert(0, "openai")
    return available_clients


def resolve_client(client_name: str) -> OpenAI:
    """Resolves a configured client name to an OpenAI-compatible client instance.
    Args:
        client_name (str): The name of the client to resolve.
    Returns:
        OpenAI: An OpenAI-compatible client instance.
    Raises:
        ValueError: If the client name is unsupported or required API keys are missing.
    """
    normalized_name = client_name.strip().lower()
    if normalized_name == "openai":
        if not openai_client:
            raise ValueError("OPENAI_API_KEY not found. Configure an API key or use the ollama client.")
        return openai_client
    if normalized_name == "ollama":
        return ollama_client
    raise ValueError(f"Unsupported client '{client_name}'. Choose from: {', '.join(get_available_client_names())}.")


def interactive_setup(current_config: dict) -> dict:
    """Prompts the user for default client and model values.
    Args:
        current_config (dict): The current configuration to use as defaults in the prompts.
    Returns:
        dict: A dictionary containing the selected "client" and "model".    
    """
    available_clients = get_available_client_names()
    default_client = current_config.get("client", DEFAULT_CONFIG["client"])
    if default_client not in available_clients:
        default_client = available_clients[0]

    selected_client = Prompt.ask(
        "Select default client",
        choices=available_clients,
        default=default_client,
    )
    selected_model = Prompt.ask(
        "Select default model",
        default=current_config.get("model", DEFAULT_CONFIG["model"]),
    ).strip()

    if not selected_model:
        raise ValueError("Model name cannot be empty.")

    return {"client": selected_client, "model": selected_model}


def run_setup_mode(args: argparse.Namespace) -> None:
    """Handles configuration setup for persisted client/model defaults.
    Args:
        args (argparse.Namespace): The command-line arguments.
    Returns:
        None
    """
    current_config = load_cli_config()
    client_provided = getattr(args, "client_provided", False)
    model_provided = getattr(args, "model_provided", False)

    no_explicit_action = not any((args.interactive, args.show, client_provided, model_provided))
    if no_explicit_action:
        args.show = True

    if args.show:
        console.print(Panel(
            f"[bold]Config file:[/bold] {CONFIG_PATH}\n"
            f"[bold]Default client:[/bold] {current_config['client']}\n"
            f"[bold]Default model:[/bold] {current_config['model']}",
            title="[bold cyan]Current Setup[/bold cyan]",
            border_style="cyan",
        ))
        if not args.interactive and not client_provided and not model_provided:
            return

    if args.interactive:
        next_config = interactive_setup(current_config)
    elif client_provided or model_provided:
        next_config = current_config.copy()
        if client_provided:
            next_config["client"] = args.client.strip().lower()
        if model_provided:
            next_config["model"] = args.model.strip()
    else:
        return

    resolve_client(next_config["client"])
    if not next_config["model"]:
        raise ValueError("Model name cannot be empty.")

    save_cli_config(next_config)
    console.print(f"[bold green]Saved setup to {CONFIG_PATH}[/bold green]")
    console.print(f"[bold green]Default client:[/bold green] {next_config['client']}")
    console.print(f"[bold green]Default model:[/bold green] {next_config['model']}")

# Import system prompts
from prompts import CODE_GENERATION_PROMPT, TEST_GENERATION_PROMPT
prompt_list = [CODE_GENERATION_PROMPT, TEST_GENERATION_PROMPT]
for prompt in prompt_list:
    if not prompt or not isinstance(prompt, str):
        raise ValueError("One of the prompts is missing or not a string. Please check the prompts.py file.")

# ─────────────────────────────────────────────────────────────
# Helper function for validating filenames
# ─────────────────────────────────────────────────────────────

def validate_filename(filename: str) -> str:
    """
    Validates and sanitizes a filename to ensure it is safe for use.
    Args:
        filename: The input filename to validate
    Returns:
        A sanitized filename with a .py extension if valid, otherwise raises ValueError.
    Raises:
        ValueError: If the filename is invalid (e.g., contains prohibited characters).
    """
    # Ensure correct file extension
    if not filename.endswith(".py"):
        # Remove any existing extension and add .py
        filename = re.sub(r'\.\w+$', '', filename) + ".py"
    
    # Ensure the filename is valid (basic check)
    if not re.match(r'^[\w\-. ]+$', filename):
        raise ValueError("Invalid filename. Use only letters, numbers, underscores, hyphens, dots and spaces.")
    
    return filename

# ─────────────────────────────────────────────────────────────
# Define functions for code generation, test generation, and saving to file
# ─────────────────────────────────────────────────────────────
def generate_code(description: str, 
                  with_tests: bool = False, 
                  save_filename: str = None,
                  tests_filename: str = None,
                  model: str = "gpt-4o-mini",
                  client: OpenAI = client,
                  max_tokens: int = 800,
                  temperature: float = 0.2) -> dict:
    """
    Generates python code from natural language description, using a model
    compatible with the OpenAI API. Optionally generates unit tests 
    (Prompt Chaining) and saves to file.

    Args:
        description: Natural language description (e.g., "a function that sorts a list")
        with_tests: If True, generates unit tests (Prompt Chaining!)
        save: If a filename is provided, saves the code
        model: Which model to use for code generation (default: "gpt-4o-mini")
        client: OpenAI API compatible client instance (default: OpenAI client)
        max_tokens: Max tokens for the response (default: 800)
        temperature: Sampling temperature for generation (default: 0.2)

    Returns:
        dict: {"code": "...", "tests": "..."} (tests only if with_tests=True)
    """

    #Validate temperature
    if not (0.0 <= temperature <= 1.0):
        raise ValueError("Temperature must be between 0.0 and 1.0")
    
    #Validate max_tokens
    if max_tokens <= 0:
        raise ValueError("max_tokens must be a positive integer")

    if not with_tests:
        # Insert the description into the code generation prompt
        console.print(f"[bold blue]Generating code for:[/bold blue]\n{description}")
        gen_prompt = CODE_GENERATION_PROMPT.format(description=description)

        with console.status("[bold green]Calling the API...[/bold green]", spinner="dots"):
            code = ask(gen_prompt, 
                           model=model, 
                           temperature=temperature, 
                           max_tokens=max_tokens, 
                           client=client
            )
        code = clean_code_output(code)
        result = {"code": code}

    else:
        # Repetitive code block
        console.print(f"[bold blue]Generating code for:[/bold blue]\n{description}")
        gen_prompt = CODE_GENERATION_PROMPT.format(description=description)

        with console.status("[bold green]Generating code...[/bold green]", spinner="dots"):
            code = ask(gen_prompt,
                           model=model, 
                           temperature=temperature, 
                           max_tokens=max_tokens, 
                           client=client
            )
        code = clean_code_output(code)
        result = {"code": code}

        # Insert the generated code into the test generation prompt
        console.print("[bold blue]Generating tests for the code...[/bold blue]")
        test_prompt = TEST_GENERATION_PROMPT.format(code=code)
        with console.status("[bold green]Generating tests...[/bold green]", spinner="dots"):
            tests = ask(test_prompt,
                           model=model, 
                           temperature=temperature, 
                           max_tokens=max_tokens, 
                           client=client
            )
        tests = clean_code_output(tests)
        result["tests"] = tests

    if save_filename:
        save_filename = validate_filename(save_filename)
        save_code(result.get("code", ""), save_filename)

    if tests_filename:
        tests_filename = validate_filename(tests_filename)
        save_code(result.get("tests", ""), tests_filename)

    return result

def clean_code_output(code: str) -> str:
    """
   Removes markdown formatting from LLM output to extract clean Python code.
    Args:
        code: Raw output from the LLM
    Returns:
        str: Clean Python code
    Example:
        Input:
        ```python
        def add(a, b):
            return a + b    ```
        Output:
        def add(a, b):
            return a + b
"""

    code = code.strip()
    if code.startswith("```python"):
        code = code[9:]
    elif code.startswith("```"):
        code = code[3:]
    if code.endswith("```"):
        code = code[:-3]
    return code.strip()

def save_code(code: str, 
              filename: str, 
              tests: str = None):
    """
    Stores code (and optionally tests) in a .py file.
    Args:
        code: Python code
        filename: Filename (e.g., "prime.py")
        tests: Optional unit tests
    Returns:
        None (saves file to disk)
    """
    # Validate and sanitize the filename
    filename = validate_filename(filename)
    
    filepath = Path(filename)
    if tests:
        full_code = f"{code}\n\n\n# ==================== TESTS ====================\n\n{tests}"
    else:
        full_code = code
    filepath.write_text(full_code)
    console.print(f"[bold green]✓ Saved to {filepath.absolute()}[/bold green]")

# ─────────────────────────────────────────────────────────────
# Define interactive mode function
# ─────────────────────────────────────────────────────────────

def interactive_mode(with_tests_argu: bool,
                     model: str,
                     client_name: str,
                     selected_client: OpenAI):
    """Runs the code generator in interactive mode, prompting the user 
    for input until they choose to exit.
    Args:
        with_tests_argu: Whether to generate tests for the code (True/False)
        model: Model name used for generation
        client_name: Name of the selected client
        selected_client: OpenAI-compatible client instance used for generation
    Returns:
        None
    """
    console.print(Panel(
        "[bold cyan]Code Generator — Interactive Mode[/bold cyan]\n"
        f"Client: [bold]{client_name}[/bold] | Model: [bold]{model}[/bold]\n"
        "Type a description or [bold]'exit'[/bold] to quit.",
        border_style="cyan"
    ))
    
    while True:
        user_input = Prompt.ask("\n[bold]Enter code description[/bold]")
        if user_input.lower() == 'exit':
            console.print("[bold yellow]Exiting interactive mode.[/bold yellow]")
            break
        else:
            description = user_input.strip()
            if description:
                # Generate code response
                result = generate_code(
                    description,
                    with_tests=with_tests_argu,
                    model=model,
                    client=selected_client,
                )
                
                console.print(Panel(
                    Syntax(result['code'], "python", theme="monokai", line_numbers=True),
                    title="[bold green]Generated Code[/bold green]",
                    border_style="green"
                ))
                # If tests were generated, print them as well
                if with_tests_argu and "tests" in result:
                    console.print(Panel(
                        Syntax(result['tests'], "python", theme="monokai", line_numbers=True),
                        title="[bold blue]Generated Tests[/bold blue]",
                        border_style="blue"
                    ))
                # Prompt to save the code to a file
                if Confirm.ask("Save to file?"):
                    filename = Prompt.ask("Enter the filename", default="output.py")
                    filename = validate_filename(filename)
                    save_code(result['code'], filename, result.get('tests'))
                else:
                    console.print("[yellow]Code not saved.[/yellow]")
    
    return None

# ─────────────────────────────────────────────────────────────
# Define CLI argument parsing
# ─────────────────────────────────────────────────────────────

def build_generation_parser() -> argparse.ArgumentParser:
    """Builds the parser used for normal code generation runs.
    Args:
        None
    Returns:
        argparse.ArgumentParser: The configured argument parser for code generation.
    """
    parser = argparse.ArgumentParser(
    description="Generate Python code from a natural-language prompt.",
    usage="%(prog)s [description_text ...] [--description TEXT] [--setup] [--client CLIENT] [--model MODEL] [--with-tests] [--save FILE | --save_tests_only FILE | --save_all FILE] [--display] [-i]",
    epilog="""
Examples:
  %(prog)s "binary search" --display
  %(prog)s --description "merge sort" --with-tests --display
  %(prog)s "prime checker" --client ollama --model llama3.2 --save prime.py
  %(prog)s "fibonacci" --with-tests --save_all fibonacci.py
  %(prog)s -i
  %(prog)s setup --help
""",
    formatter_class=RichHelpFormatter,
)
    parser.add_argument('description_text', nargs='*', help='Optional positional description of the code to generate')
    parser.add_argument('--description', type=str, help='A description of the code to generate')
    parser.add_argument('--setup', action='store_true', help='Open interactive setup mode (same as running: setup)')
    parser.add_argument('--client', type=str, choices=['openai', 'ollama'], default=None, help='Which client to use for this run, overriding the configured default')
    parser.add_argument('--with-tests', action='store_true', help='Whether to generate tests for the code')
    parser.add_argument('--temperature', type=float, nargs='?', default=0.2, help='Sampling temperature for generation, optional (default: 0.2)')
    parser.add_argument('--model', type=str, nargs='?', default=None, help='Which model to use for this run, overriding the configured default')
    parser.add_argument('--list_ollama_models', action='store_true', help='List available Ollama models and exit')
    parser.add_argument('--max-tokens', type=int, nargs='?', default=800, help='Max tokens for the response, optional (default: 800)')
    parser.add_argument('--save', type=str, default=None, help='Save the generated code to a file with the given filename (e.g., "prime.py")')
    parser.add_argument('--save_tests_only', type=str, default=None, help='Whether to save the generated tests to the file only')
    parser.add_argument('--save_all', type=str, default=None, help='Whether to save both code and tests to the file (if tests are generated) - one file name needed, the tests will be filename_tests.py')
    parser.add_argument('--display', action='store_true', help='Whether to display the generated code in the console')
    parser.add_argument('-i', action='store_true', help='Whether to generate code interactively')
    parser.add_argument("--json_output", type=str, default=None, help='Save the output to a file in JSON format')
    parser.set_defaults(command='generate')
    return parser

def build_setup_parser() -> argparse.ArgumentParser:
    """Builds the parser used for persistent setup/configuration.
    Args:
        None
    Returns:
        argparse.ArgumentParser: The configured argument parser for setup mode.
    """
    parser = argparse.ArgumentParser(
        prog=f"{Path(sys.argv[0]).name} setup",
        description="Configure the default client and model used by the rich code generator.",
        epilog="""
Examples:
  %(prog)s --show
  %(prog)s --client ollama --model llama3.2
  %(prog)s --interactive
""",
        formatter_class=RichHelpFormatter,
    )
    parser.add_argument('--client', type=str, choices=['openai', 'ollama'], default='openai', help='Persist the default client for future runs (default: openai)')
    parser.add_argument('--model', type=str, default='gpt-4o-mini', help='Persist the default model for future runs (default: gpt-4o-mini)')
    parser.add_argument('--show', action='store_true', help='Show the currently saved setup values')
    parser.add_argument('-i', '--interactive', action='store_true', help='Prompt for setup values interactively')
    parser.set_defaults(command='setup')
    return parser

def validate_json_output_payload(output_data: dict) -> None:
    """Validates JSON output payload against the schema.
    Args:
        output_data: The payload to validate before saving.
    Returns:
        None
    Raises:
        ValueError: If payload does not satisfy the schema.
    """
    try:
        validate(instance=output_data, schema=JSON_OUTPUT_SCHEMA)
    except ValidationError as exc:
        field_path = ".".join(str(part) for part in exc.path)
        location = f" at '{field_path}'" if field_path else ""
        raise ValueError(f"Invalid JSON output payload{location}: {exc.message}") from exc


def define_json_output(model_name: str,
                       client_name: str,
                       description: str,
                       temperature: float,
                       max_tokens: int,
                       with_tests: bool,
                       result: dict,
                       filename: str):
    """Save generated output to a schema-validated JSON file.
    Args:
        model_name: The model used for generation.
        client_name: The client used for generation.
        description: The generation prompt description.
        temperature: The sampling temperature used for generation.
        max_tokens: The max token limit used for generation.
        with_tests: Whether tests were requested for generation.
        result: The dictionary containing generated code and optional tests.
        filename: The output JSON filename.
    Returns:
        None
    """
    output_data = {
        "model": model_name,
        "client": client_name,
        "description": description,
        "temperature": temperature,
        "max_tokens": max_tokens,
        "with_tests": with_tests,
        "created_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "code": result.get("code", ""),
    }
    if "tests" in result:
        output_data["tests"] = result["tests"]

    validate_json_output_payload(output_data)

    output_path = Path(filename)
    output_path.write_text(json.dumps(output_data, indent=2), encoding="utf-8")
    console.print(f"[bold green]✓ JSON output saved to {output_path.absolute()}[/bold green]")

    return None

def define_cli_args(argv=None):
    """Defines the command-line arguments for the code generator CLI.
    Args:
        argv (list, optional): A list of command-line arguments to parse.
    Returns:
        argparse.Namespace: Parsed command-line arguments
    """
    argv = sys.argv[1:] if argv is None else argv
    if argv and argv[0] == 'setup':
        setup_argv = argv[1:]
        args = build_setup_parser().parse_args(setup_argv)
        args.client_provided = any(token == '--client' or token.startswith('--client=') for token in setup_argv)
        args.model_provided = any(token == '--model' or token.startswith('--model=') for token in setup_argv)
        return args
    return build_generation_parser().parse_args(argv)

# ─────────────────────────────────────────────────────────────
# main()
# ─────────────────────────────────────────────────────────────

def main():

    # Get CLI arguments
    args = define_cli_args()

    if args.command == 'setup':
        run_setup_mode(args)
        return

    if args.setup:
        run_setup_mode(argparse.Namespace(
            client=None,
            model=None,
            show=True,
            interactive=False,
            client_provided=False,
            model_provided=False,
            command='setup',
        ))
        return

    if args.list_ollama_models:
        try:
            models = get_ollama_models()
        except Exception as exc:
            console.print(f"[bold red]Failed to list Ollama models:[/bold red] {exc}")
            return

        if models:
            console.print("[bold green]Available Ollama models:[/bold green]")
            for model in models:
                console.print(Text(" - ") + format_ollama_model_name(model), highlight=False)
        else:
            console.print("[yellow]No Ollama models found.[/yellow]")
        return

    config = load_cli_config()
    client_name = args.client or config['client']
    model_name = args.model or config['model']
    selected_client = resolve_client(client_name)

    positional_description = ' '.join(args.description_text).strip()
    description = args.description or positional_description

    if args.description and positional_description:
        console.print("[bold red]Please provide the description either as positional text or with --description, not both.[/bold red]")
        return

    if args.i:
        interactive_mode(
            with_tests_argu=args.with_tests,
            model=model_name,
            client_name=client_name,
            selected_client=selected_client,
        )
    else:
        if description:
            # Handle the saving logic based on the different save flags and validate                     
            filename = None
            tests_filename = None

            save_mode = (isinstance(args.save, str), isinstance(args.save_tests_only, str), isinstance(args.save_all, str), args.with_tests)
            match save_mode:
                case (True, False, False, _):
                    filename = validate_filename(args.save)
                case (False, True, False, True):
                    tests_filename = validate_filename(args.save_tests_only)
                case (False, False, True, True):
                    filename = validate_filename(args.save_all)
                    tests_filename = filename.replace(".py", "_tests.py")
                case (True, True, False, True):
                    filename = validate_filename(args.save)
                    tests_filename = validate_filename(args.save_tests_only)
                case (_, True, _, False):
                    raise ValueError("Cannot save tests only if --with-tests is not set.")
                case (_, False, True, False):
                    raise ValueError("Cannot save all if --with-tests is not set.")
                case (False, False, False, False):
                    pass
                case _: # Other flags should pass without a check
                    pass 
            
            result = generate_code(description, 
                                with_tests=args.with_tests, 
                                save_filename=filename if filename else None,
                                tests_filename=tests_filename if tests_filename else None,
                                model=model_name,
                                client=selected_client,
                                max_tokens=args.max_tokens, 
                                temperature=args.temperature)
            if args.json_output:
                define_json_output(
                    model_name=model_name,
                    client_name=client_name,
                    description=description,
                    temperature=args.temperature,
                    max_tokens=args.max_tokens,
                    with_tests=args.with_tests,
                    result=result,
                    filename=args.json_output,
                )
            if args.display:
                console.print(Panel(
                    Syntax(result['code'], "python", theme="monokai", line_numbers=True),
                    title="[bold green]Generated Code[/bold green]",
                    border_style="green"
                ))
                if args.with_tests and "tests" in result:
                    console.print(Panel(
                        Syntax(result['tests'], "python", theme="monokai", line_numbers=True),
                        title="[bold blue]Generated Tests[/bold blue]",
                        border_style="blue"
                    ))
        else:
            console.print("[yellow]Please provide a code description as positional text, with --description, or use interactive mode (-i). Use --help for more options.[/yellow]")

if __name__ == "__main__":
    main()